apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  type: NodePort
  ports:
  - name: "serv-service"
    port: 8080
    targetPort: 8080
  selector:
    app: server
